apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T13:26:58Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "4025"
  uid: 71ae7da9-fdfd-44c9-b415-304dfa460761
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.107.69.122
  clusterIPs:
  - 10.107.69.122
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32459
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
